meta_title: "Holly"
meta_description: "Your movie list, just better."
meta_image: "metaclap.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@hollymovielist" # indispensable pour les Twitter Cards
