meta_title: "Clap!"
meta_description: "Il n'a jamais été aussi simple de gérer sa watchlist"
meta_image: "metaclap.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@weclap" # indispensable pour les Twitter Cards
